package parser

import (
	"sync"
	"time"

	"github.com/marcosaugustodev/cli-dm/internal/protocol"
)

// AgentState tracks the current state of an agent for event generation.
// The adapter writes to this; it emits events on state transitions.
type AgentState struct {
	mu            sync.Mutex
	ID            string
	CurrentAction protocol.ActionType
	CurrentDetail string
	ActionStart   time.Time
	ErrorCount    int
	IsBlocked     bool
	BlockedBy     string
}

// NewAgentState creates a new state tracker for an agent
func NewAgentState(id string) *AgentState {
	return &AgentState{
		ID:            id,
		CurrentAction: protocol.ActionIdle,
	}
}

// TransitionResult holds events generated by a state transition
type TransitionResult struct {
	Events []protocol.Event
}

// Transition moves the agent to a new action state, emitting action.end
// for the previous action (if any) and action.start for the new one.
// If the new action is the same as the current one, only the detail is updated
// (no events emitted) to avoid spam.
// If the agent was blocked and transitions to a real action, auto-resolves the blocker.
func (s *AgentState) Transition(action protocol.ActionType, detail string) TransitionResult {
	s.mu.Lock()
	defer s.mu.Unlock()

	now := protocol.NowMs()
	var events []protocol.Event

	// Auto-resolve blocker when transitioning to a real action
	if s.IsBlocked && action != protocol.ActionIdle && action != protocol.ActionBlocked {
		s.IsBlocked = false
		s.BlockedBy = ""
		resolveEv, _ := protocol.NewEvent(protocol.BlockerResolve{
			Type:    protocol.TypeBlockerResolve,
			AgentID: s.ID,
			Ts:      now,
		})
		events = append(events, resolveEv)
	}

	// Same action with same detail — no-op
	if s.CurrentAction == action && s.CurrentDetail == detail {
		return TransitionResult{Events: events}
	}

	// End previous action (if not idle)
	if s.CurrentAction != protocol.ActionIdle {
		endEvt, _ := protocol.NewEvent(protocol.ActionEnd{
			Type:    protocol.TypeActionEnd,
			AgentID: s.ID,
			Action:  s.CurrentAction,
			Detail:  s.CurrentDetail,
			Result:  "unknown",
			Ts:      now,
		})
		events = append(events, endEvt)
	}

	// Start new action
	s.CurrentAction = action
	s.CurrentDetail = detail
	s.ActionStart = time.Now()

	if action != protocol.ActionIdle {
		startEvt, _ := protocol.NewEvent(protocol.ActionStart{
			Type:    protocol.TypeActionStart,
			AgentID: s.ID,
			Action:  action,
			Detail:  detail,
			Ts:      now,
		})
		events = append(events, startEvt)
	}

	return TransitionResult{Events: events}
}

// MarkError increments the error count and optionally emits an agent.error event
func (s *AgentState) MarkError(message string) protocol.Event {
	s.mu.Lock()
	s.ErrorCount++
	s.mu.Unlock()

	ev, _ := protocol.NewEvent(protocol.AgentError{
		Type:    protocol.TypeAgentError,
		AgentID: s.ID,
		Message: message,
		Ts:      protocol.NowMs(),
	})
	return ev
}

// MarkBlocked marks the agent as blocked
func (s *AgentState) MarkBlocked(blockerType protocol.BlockerType, blockedBy, detail string) protocol.Event {
	s.mu.Lock()
	s.IsBlocked = true
	s.BlockedBy = blockedBy
	s.mu.Unlock()

	ev, _ := protocol.NewEvent(protocol.BlockerHit{
		Type:        protocol.TypeBlockerHit,
		AgentID:     s.ID,
		BlockerType: blockerType,
		BlockedBy:   blockedBy,
		Detail:      detail,
		Ts:          protocol.NowMs(),
	})
	return ev
}

// Snapshot returns the current state for the state.snapshot event
func (s *AgentState) Snapshot() protocol.AgentSnapshot {
	s.mu.Lock()
	defer s.mu.Unlock()
	return protocol.AgentSnapshot{
		AgentID:       s.ID,
		CurrentAction: s.CurrentAction,
		CurrentDetail: s.CurrentDetail,
		IsBlocked:     s.IsBlocked,
		ErrorCount:    s.ErrorCount,
	}
}
